# Generated by Django 3.2 on 2022-05-16 15:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_order_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmed_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата/время подтверждения'),
        ),
        migrations.AddField(
            model_name='order',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата/время создания'),
        ),
        migrations.AddField(
            model_name='order',
            name='fulfilled_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата/время исполнения'),
        ),
    ]
