# Generated by Django 3.2 on 2022-05-16 15:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_auto_20220516_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='confirmed_on',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата/время подтверждения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_on',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата/время создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='fulfilled_on',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата/время исполнения'),
        ),
    ]
