# Generated by Django 3.2 on 2022-05-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_auto_20220516_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.SmallIntegerField(choices=[(0, 'Наличные'), (1, 'Электронная')], db_index=True, default=0, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Необработанный'), (1, 'Обработанный'), (2, 'Отмененный'), (3, 'Исполненный')], db_index=True, default=0, verbose_name='Статус заказа'),
        ),
    ]
