# Generated by Django 3.2 on 2022-05-18 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_order_assigned_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='assigned_restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='foodcartapp.restaurant', verbose_name='Готовится в ресторане'),
        ),
    ]
