# Generated by Django 3.2 on 2022-06-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_alter_order_assigned_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.SmallIntegerField(choices=[(0, 'Не выбрано'), (1, 'Наличные'), (2, 'Электронная')], db_index=True, default=0, verbose_name='Способ оплаты'),
        ),
    ]
