# Generated by Django 3.2 on 2022-06-02 18:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Адрес')),
                ('lat', models.FloatField(null=True, verbose_name='Положение по широте')),
                ('lon', models.FloatField(null=True, verbose_name='Положение по долготе')),
                ('fetched_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата запроса к геокодеру')),
            ],
        ),
    ]
